# Generated by Django 5.2.5 on 2025-11-03 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=254)),
                ('precio', models.IntegerField()),
                ('imagen', models.ImageField(upload_to='productos')),
            ],
        ),
    ]
