# Generated by Django 5.2.5 on 2025-11-03 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.ManyToManyField(to='tienda.categoria'),
        ),
    ]
