# Generated by Django 5.2.8 on 2025-11-13 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0006_alter_detalle_venta_cantidad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='costo_total_con_iva',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='costo_total_sin_iva',
        ),
    ]
