# Generated by Django 5.2.8 on 2025-11-13 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0007_remove_venta_costo_total_con_iva_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle_venta',
            name='precio_unitario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
