# Generated by Django 5.2.8 on 2025-11-28 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0009_venta_estado_alter_venta_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='codigo_barra',
            field=models.CharField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
